# primary dataset
with dataset AS (
  SELECT h.fips, 
  SUM(h.count) AS xvar, 
  SUM(h.count) - AVG(SUM(h.count)) over () AS zvar
# The dataset used for this query is generated by my EDA notebook/script 
# please check the .py script in the github
  FROM `week-8-assignment-478604.winter2026.homogeneity` AS h
  #WHERE clr = 'beige' OR clr = 'brown' OR clr = 'tan' OR clr = 'cocoa' OR clr = 'coffee'
  GROUP BY fips
),
# variables
avg_df AS (
  SELECT AVG(h.xvar) AS mu
  FROM dataset AS h
),
var_df AS (
  SELECT var_pop(zvar) AS pop_var
  from dataset
)

, local_morans AS (
SELECT CAST(adj.county_code AS INT64) AS fips, (avg(xi.zvar) / (select pop_var from var_df)) * ((1/count(xi.zvar)) * sum(xj.zvar)) AS local, count(xi.zvar) as n_neighbors
FROM `week-8-assignment-478604.winter2026.adjacent_counties` AS adj
JOIN dataset AS xi
ON CAST(adj.county_code AS INT64) = xi.fips
JOIN dataset AS xj
ON CAST(adj.neighbors_code AS INT64) = xj.fips
GROUP BY adj.county_code
)

#SELECT SUM(local)/58 FROM local_morans
, county_geom AS (
SELECT CAST(county_fips_code AS INT64) AS fips, county_geom as geometry
FROM `bigquery-public-data.geo_us_boundaries.counties`
WHERE state_fips_code = '06'
)

SELECT county_geom.fips, local_morans.local, county_geom.geometry
FROM local_morans
JOIN county_geom
ON county_geom.fips = local_morans.fips
